poeditor/urls.py
from django.contrib import admin
from django.conf.urls import patterns, include, url


from poeditor_app.views import panel_page


urlpatterns = patterns('',
    url(r'^$',panel_page,name='panel_page'),
    url(r'^poeditor/', include('poeditor_app.urls',namespace='poeditor_app')),
    url(r'^admin/', include(admin.site.urls)),
)

poeditor_app/urls.py
from django.conf.urls import patterns, url


from poeditor_app.views import edit_panel_page,search_panel_page


urlpatterns = patterns('',
  url(r'^edit/panel/page/$',edit_panel_page,name='edit_panel_page'),
  url(r'^search/panel/page/$',search_panel_page,name='search_panel_page'),
)

poeditor_app/models.py
from django.db import models

# Create your models here.

poeditor_app/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.conf import settings


from poeditor import constants


class PanelPageForm(forms.Form):
    LANGUAGES = (('--', u'-------'),) + settings.LANGUAGES
    submit_type = forms.CharField(max_length=20)
    filled_languages = forms.ChoiceField(choices=LANGUAGES,required=False)
    unfilled_languages = forms.ChoiceField(choices=LANGUAGES,required=False)
    groups = forms.ChoiceField(choices=constants.GROUPS,required=False)
    searchtext = forms.CharField(max_length=100)

class EditPanelPageForm(forms.Form):
    groups = forms.ChoiceField(choices=constants.GROUPS, required=False, widget=forms.Select(attrs={'disabled':'true', 'readonly':'readonly'}))
    information = forms.CharField(widget=forms.Textarea)
    strid=forms.CharField(widget=forms.TextInput(attrs={'class':'disabled', 'readonly':'readonly'}))
    unfilled_languages = forms.CharField(max_length=20, required=False)
    filled_languages = forms.CharField(max_length=20, required=False)
    fuzzy = forms.BooleanField(required=False)

class SearchPanelPageForm(forms.Form):
    search_text = forms.CharField(max_length=100)
    fill_language = forms.CharField(max_length=50)
    unfill_languages = forms.CharField(max_length=50)
    group = forms.CharField(max_length=50)

poeditor_app/views.py
# -*- coding: utf-8 -*-
import polib


from django.conf import settings
from django.shortcuts import render
from django.views.generic import View
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse


from poeditor import constants
from poeditor.mixin import PaginatorMixin
from poeditor.redis_cache import redis_cache
from poeditor_app.forms import PanelPageForm,EditPanelPageForm,SearchPanelPageForm


class PanelPage(View,PaginatorMixin):

    def get(self, request, *args, **kwargs):
        response = {}
        filled_languages = request.GET.get('filled_languages')
        unfilled_languages = request.GET.get('unfilled_languages')
        groups = request.GET.get('groups')
        searchtext = request.GET.get('searchtext')
        print "searchtext",searchtext

        is_search = False
        if searchtext :
            searchtext = searchtext.lower()
            is_search = True

        print "is_search",is_search

        if not filled_languages:
            filled_languages = "--"
        if not unfilled_languages:
            unfilled_languages = "--"
        if not groups :
            groups = "all"

        if filled_languages and unfilled_languages and filled_languages == unfilled_languages :
            unfilled_languages = "--"
            filled_languages = "--"

        panel_form = PanelPageForm()
        panel_form.fields['filled_languages'].initial = filled_languages
        panel_form.fields['unfilled_languages'].initial = unfilled_languages
        panel_form.fields['groups'].initial = groups
        panel_form.fields['searchtext'].initial = searchtext

        cache_id_data = redis_cache.get_cache(settings.CACHE_IDS)
        cache_language_data = redis_cache.get_cache(settings.CACHE_LANGUAGES)
        cache_id_ocurrence = redis_cache.get_cache(settings.CACHE_OCURRENCE)
        cache_group_data = redis_cache.get_cache(settings.CACHE_GROUP)
        cache_id_list = redis_cache.get_cache(settings.CACHE_IDS_LIST)

        group_data = cache_group_data[groups]

        response['po_data'] = []
        response['page_size'] = []
        is_first = True
        first_key = ""
        last_key = ""
        page_number = 1

        if not is_search:
            for key in cache_id_list:
                value = cache_id_data[key]
                fill_flag = False
                unfill_flag = False
                for dicts in cache_language_data[value]:

                    dummy_filled_languages = filled_languages
                    if filled_languages == "--":
                        dummy_filled_languages = dicts['language']

                    dummy_unfilled_languages = unfilled_languages
                    if unfilled_languages == "--":
                        dummy_unfilled_languages = dicts['language']

                    if dummy_filled_languages == dicts['language'] and dicts['str'] and value in group_data:
                        fill_flag = True
                    if dummy_unfilled_languages == dicts['language'] and not dicts['str'] and value in group_data:
                        unfill_flag = True

                    if fill_flag and unfill_flag :
                        ocurrences = cache_id_ocurrence[key]
                        trans_lang = []
                        for lang in cache_language_data[value]:
                            if lang['str'] :
                                trans_lang.append(constants.LANGUAGES[lang['language']])
                        if {'id':key,'str':value,'trans_lang':trans_lang,"ocurrences":ocurrences} not in response['po_data']:
                            response['po_data'].append({'id':key,'str':value,'trans_lang':trans_lang,"ocurrences":ocurrences})
                            last_key = key
                            if is_first :
                                first_key = key
                                is_first = False
                            self.increase_page_size()
                            if self.is_page_size_large_to_max_size():
                                self.page_size = 0
                                response['page_size'].append([page_number,first_key,key])
                                page_number = page_number + 1
                                is_first = True

        else:
            for key in cache_id_list:
                value = cache_id_data[key]
                fill_flag = False
                unfill_flag = False
                for dicts in cache_language_data[value]:
                    if searchtext in dicts['str'].lower() or searchtext in value.lower():

                        dummy_filled_languages = filled_languages
                        if filled_languages == "--":
                            dummy_filled_languages = dicts['language']

                        dummy_unfilled_languages = unfilled_languages
                        if unfilled_languages == "--":
                            dummy_unfilled_languages = dicts['language']

                        if dummy_filled_languages == dicts['language'] and dicts['str'] and value in group_data:
                            fill_flag = True
                        if dummy_unfilled_languages == dicts['language'] and not dicts['str'] and value in group_data:
                            unfill_flag = True

                        if fill_flag and unfill_flag:
                            ocurrences = cache_id_ocurrence[key]
                            trans_lang = []
                            for lang in cache_language_data[value]:
                                if lang['str'] :
                                    trans_lang.append(constants.LANGUAGES[lang['language']])
                            if {'id':key,'str':value,'trans_lang':trans_lang,"ocurrences":ocurrences} not in response['po_data']:
                                response['po_data'].append({'id':key,'str':value,'trans_lang':trans_lang,"ocurrences":ocurrences})
                                last_key = key
                                if is_first :
                                    first_key = key
                                    is_first = False

                                self.increase_page_size()
                                if self.is_page_size_large_to_max_size():
                                    self.page_size = 0
                                    response['page_size'].append([page_number,first_key,key])
                                    page_number = page_number + 1
                                    is_first = True



        response['page_size'].append([page_number,first_key,last_key])
        response['panel_form'] = panel_form

        search_form = SearchPanelPageForm()
        search_form.fields['group'].initial = groups
        search_form.fields['fill_language'].initial = filled_languages
        search_form.fields['unfill_languages'].initial = unfilled_languages
        search_form.fields['search_text'].initial = searchtext
        response['search_form'] = search_form

        if groups == "all":
            response['groups'] = ""
        else:
            response['groups'] = groups

        try:
            response['load_key'] = response['page_size'][0][2]
        except Exception, e:
            response['load_key'] = response['po_data'][-1]["id"]

        return render(request, 'poeditor_app/panel-html.html', response)

panel_page = PanelPage.as_view()


class EditPanelPage(View):

    def get(self, request, *args, **kwargs):
        response ={}
        cache_language_data = redis_cache.get_cache(settings.CACHE_LANGUAGES)
        unfilled_language = request.GET.get('unfilled_language')
        filled_languages = request.GET.get('filled_language')
        submit_language = request.GET.get('submit_language')
        if submit_language :
            unfilled_language = constants.LANGUAGES_VAL[submit_language]
        languages = settings.DEFAULT_LANGUAGE

        if unfilled_language == "--":
            if filled_languages == "--":
                languages = settings.DEFAULT_LANGUAGE
            else:
                languages = filled_languages
        else :
            languages = unfilled_language
        
        strid = request.GET.get('str')
        select_group = request.GET.get('select_group')
        id_data_list = cache_language_data[strid]

        edit_form = EditPanelPageForm()
        edit_form.fields['groups'].initial = select_group  
        edit_form.fields['strid'].initial = strid  
        edit_form.fields['unfilled_languages'].initial = unfilled_language  
        edit_form.fields['filled_languages'].initial = filled_languages                 
        
        cache_language_data = redis_cache.get_cache(settings.CACHE_LANGUAGES)
        fuzzy_language = cache_language_data[strid]
        for fuzzy in fuzzy_language:
            if fuzzy['language'] == languages and fuzzy['is_fuzzy'] :
                edit_form.fields['fuzzy'].initial = True

        response['language'] = []
        for lang in  settings.LANGUAGES:
            id_str = ""
            for l in id_data_list:
                if l['language'] == lang[0]:
                    id_str = l['str']
            if lang[0] == languages:
                response['language'].append({"lang":lang[1],"select":True,"str":id_str})
                edit_form.fields['information'].initial = id_str
            else:
                response['language'].append({"lang":lang[1],"str":id_str})
        if request.GET.get('errors') :
            response['errors'] = request.GET.get('errors')
        response['select_group'] = select_group
        response['edit_form'] = edit_form
        return render(request, 'poeditor_app/edit-page.html', response)


    def post(self, request, *args, **kwargs):
        cache_language_data = redis_cache.get_cache(settings.CACHE_LANGUAGES)
        edit_form = EditPanelPageForm(request.POST) 
        if edit_form.is_valid():
            information = edit_form.cleaned_data['information']

templates/poeditor_app/edit-page.html
{% extends "main_base.html" %}
{% block head_title %}Edit{% endblock %}
{% load profile_filters %}
{% block content %}
<div class="mar-top-15">
  <div class="col-sm-6">
    <div class="box border success">
      <div class="box-body  no-more-tables">
        <form method="post" action="{% url 'poeditor_app:edit_panel_page' %}">
          {% csrf_token %}
          {{edit_form.unfilled_languages | hiddenfiled }}
          {{edit_form.filled_languages | hiddenfiled }}
          <p class="text-danger"></p>
          <div class="form-group ">
            <label class="control">Group</label>
            {{edit_form.groups | addclass:"form-control"}}
            <p class="text-danger"></p>
          </div>
          <div class="form-group ">
            <label class="control">Name</label>
            {{edit_form.strid | addclass:"form-control"}}
            <p class="text-danger"></p>           
          </div>     
          <div class="form-group ">
            <label class="control">fuzzy</label>
            {{edit_form.fuzzy}}
            {{edit_form.check}}
            <p class="text-danger"></p>           
          </div>        
          <div class="form-group ">
            <label class="control">Translation</label>
            {{edit_form.information |addclass:"form-control" }}
            <p class="text-danger"></p>
          </div>
          <div class="text-right"> <a class="btn btn-default" href="" disabled="true">Delete</a> <a class="btn btn-default" href="{% url 'panel_page' %}">Back</a>
            <button type="submit" class="btn btn-success">Save</button>
          </div>
        </form>
      </div>
    </div>
    <div class="col-md-4"> <!-- BOX --> 
    </div>
  </div>
  <div class="col-sm-6">
    <div class="box border success">
      <div class="box-body  no-more-tables">
        <div class="list-group" > 
        <form action="{% url 'poeditor_app:edit_panel_page' %}" method="GET">
          <input type="hidden" value="english" name="submit_language" class="submit_language"/>
          <input type="hidden" name="select_group" class="select_group" value="{{select_group}}"/>
          <input type="hidden" value="" name="str"/>
          {% for langs in language %}

          <a {% if langs.select %} class="list-group-item active" {% else %} class="list-group-item " {% endif %} href="#" str="{{langs.lang}}"> <span class="game_type_item">{{langs.str}} &nbsp; <span class="label label-success"> {{langs.lang}}</span></span>
            </a> 
          {% endfor %}
          </form>
        </div>
      </div>
    </div>
    <div class="col-md-4"> <!-- BOX --> 
    </div>
  </div>
  <div>{{errors}}</div>
</div>
<script>

$('input[name="str"]').val($('#id_strid').val());
$(document).on("click", ".list-group-item ", function (){
$(this).parent().children("input[name='submit_language']").val($(this).attr("str"));
$(this).parents("form").submit();
});

</script>
{% endblock %}

templates/poeditor_app/panel-html.html
{% extends "main_base.html" %}
{% block head_title %}Panel Page{% endblock %}
{% load profile_filters %}
{% block content %}
<div class="col-md-12">
  <div class="box border success">
    <div class="box-body  ">
      <form action="{% url 'poeditor_app:search_panel_page' %}" method="GET" id="form_search" >
        <div class="col-sm-12">
          <p class="text-danger"></p>
          <div class="form-group">
            <div class="input-group">
              {{search_form.search_text  | placeholder:"Search" | addclass:"form-control"}}
              {{search_form.group | hiddenfiled}}
              {{search_form.fill_language | hiddenfiled}}
              {{search_form.unfill_languages | hiddenfiled}}
              <span class="input-group-btn">
              <button id="bt_search" class="btn btn-default" type="button"><span class="glyphicon glyphicon-search"></span> </button>
              </span></div>
          </div>
        </div>
      </form>
      <form action="{% url 'panel_page' %}" method="GET" id="form_language">
        <div class="clearfix"></div>
        <div class="col-sm-4">
          <div class="form-group ">
            <label class="control">Language</label>
            {{panel_form.filled_languages | addclass:"form-control" }}
            <p class="text-danger"></p>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="form-group ">
            <label class="control">Language unfilled</label>
            {{panel_form.unfilled_languages | addclass:"form-control" }}
            <p class="text-danger"></p>
          </div>
        </div>
        {{panel_form.searchtext  | hiddenfiled}}
        <div class="col-sm-4">
          <div class="form-group ">
            <label class="control">Group</label>
            {{panel_form.groups | addclass:"form-control"}}
            <p class="text-danger"></p>
          </div>
        </div>
        <div class="col-sm-12 text-right clearfix"> <a class="btn btn-default" href="{% url 'panel_page' %}">Reset</a>
          <button type="button" class="btn btn-default" id="fill_unfill_submit_form">Submit</button>
        </div>
      </form>
      <div class="clearfix"></div>
      <hr>

      <table class="table table-bordered">
        <thead>
          <tr>
            <th>id</th>
            <th>Name</th>
            <th>Group</th>
            <th></th>
            <th></th>
            <th class="hide">Ocurrence</th>
          </tr>
        </thead>
        <tbody id="table_data">
        {% for data in po_data %}
          {% if data.id <= load_key %}
            <tr class="entry" key_val="{{data.id}}">
            {% else %}
            <tr class="entry hide" key_val="{{data.id}}">
            {% endif %}
            <form action="{% url 'poeditor_app:edit_panel_page' %}" method="GET">
            <td>
              {{data.id}}
              <input type="hidden" value="{{data.id}}" name="id_val" />
            </td>
            <td>
              {{data.str}}
              <input type="hidden" value="{{data.str}}" name="str" />
            </td>
            <td>{{groups}}</td>
            <td class="green_label">
            <input type="hidden" value="" name="submit_language" class="submit_language"/>
            {%for lang in data.trans_lang%}
              <a href="javascript:void(0)" class="lanedit label label-success">{{lang}}</a>
            {%endfor%}
            </td>
            <td>
            <button type="button" class="edit_button btn btn-info">Edit</button>
            <input type="hidden" value="" name="unfilled_language" class="unfilled_language"/>
            <input type="hidden" value="" name="filled_language" class="filled_language"/>
            <input type="hidden" value="" name="select_group" class="select_group"/>
            </td>
            <td class="hide">
              {%for ocur,number in data.ocurrences%}
             <a href="#"> {{ocur}}:{{number}} </a> <br>
              {%endfor%}
            </td>
             </form>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  <div class="col-md-12">
 
  
<nav class="text-center">
  <ul class="pagination">
 {% for page in page_size %}
    <li class="mar_bottonm_10" >
    <a href="#" class="page" page_number="{{page.0}}" first_key="{{page.1}}" last_key="{{page.2}}"> <span> {{page.0}} </span> </a> </li>
       {%endfor%}
  </ul>
</nav>
  </div>
</div>

<script type="text/javascript">
$(".page").first().parent().attr("class","mar_bottonm_10 active");
$(document).on("click", ".page", function () {
    var page_number = parseInt($(this).attr("page_number"));
    var first_key = parseInt($(this).attr("first_key"));
    var last_key = parseInt($(this).attr("last_key"));
    $(".entry").each(function(){
      $(this).attr("class","entry") ;
      key_val = parseInt($(this).attr("key_val"));
      if (key_val>=first_key && key_val<=last_key){
        $(this).show();
      }
      else{
        $(this).hide();
      }
    });
    $(".page").each(function(){
      $(this).parent().attr("class","mar_bottonm_10");
    });
    $(this).parent().attr("class","mar_bottonm_10 active");
});

/*$(document).on("keyup", "#id_search_text", function () {
  if ($(this).val()){
  }else{
    $("#form_language").submit();
  }

});
*/

$(document).on("click", ".lanedit", function (){

  $(this).parent().children("input").val($(this).text());
  $(this).parents("tr").children("form").submit();
});


</script>

<script type="text/javascript" src="/static/js/panel-html.js"></script>
{% endblock %}